config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  resources :users

  
  get "/sign-in",to: "sessions#new", as: :sign_in
  get "/log-out", to: "sessions#destroy", as: :log_out
  get "/new", to: "sessions#new"
  post "/create", to: "sessions#create", as: :create_session
  get "my-posts", to: "posts#my_posts", as: :my_posts
  get "my-comments", to: "comments#my_comments", as: :my_comments
  root 'posts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row">
      <div class="large-12 columns">
        <div class="nav-bar right">
         <ul class="button-group">
           <% if session[:user_id] %>
            <li><%= link_to "My Profile", user_path(session[:slug]), class: "button" %></li>
            <li><%= link_to "Log Out", log_out_path, class: "button" %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_path, class: "button" %></li>
            <li><%= link_to "Sign In", sign_in_path, class: "button" %></li>
          <% end %>
          </ul>
        </div>
        <h1>Blog <small>This is my blog. It's awesome.</small></h1>
        <hr/>
      </div>
    </div>
    <div class="row">
      <div class="large-9 columns" role="content">
        <%= yield %>
      </div>
      <aside class="large-3 columns">
        <h5>Categories</h5>
        <ul class="side-nav">
          <li><a href="/">Home</a></li>
          <li><%= link_to "My Posts" , my_posts_path %></li>
          <li><%= link_to "My Comments", my_comments_path %></li>
        </ul>
        <% if @featured_post %>
          <div class="panel">
            <h5>Featured</h5>
            <p><%= @featured_post.content %></p>
            <%= link_to 'Read More →', @featured_post %>
          </div>
        <% end %>
      </aside>
    </div>
    <footer class="row">
      <div class="large-12 columns">
        <hr/>
        <div class="row">
          <div class="large-6 columns">
            <p>© Copyright no one at all. Go to town.</p>
          </div>
          <div class="large-6 columns"></div>
        </div>
      </div>
    </footer>
  </body>
</html>